# Name of your application. Used to uniquely configure containers.
service: viewers

# Name of the container image.
image: cfaz-net/viewers

# Deploy to these servers.
servers:
  web:
    hosts:
      - 35.196.94.85
    options:
      add-host: host.docker.internal:host-gateway

# Credentials for your image host.
registry:
  server: ghcr.io
  username: Deploy
  password:
    - GITHUB_TOKEN

# Use a different ssh user than root
ssh:
  user: deploy

# Configure builder setup.
builder:
  arch: amd64
  cache:
    type: gha
  secrets:
    - GITHUB_TOKEN

# Configure kamal-proxy.
proxy:
  host: dicomviewer.cfaz.net
  app_port: 8080
  ssl: true
  healthcheck:
    path: /

# Use accessory services (secrets come from .env).
accessories:
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.8.2
    volumes:
      - '/:/host:ro'
    roles:
      - web
    options:
      publish:
        - '9100:9100'

  promtail:
    image: grafana/promtail:2.9.2
    files:
      - './config/promtail_config.yml:/etc/promtail/promtail_config.yml'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - '/var/log:/var/log'
    cmd: -config.file=/etc/promtail/promtail_config.yml
    roles:
      - web
